In [1]:
import numpy as np
df=np.load('clean_data.pkl',allow_pickle=True)

In [2]:
df[0]

[[1, 3, 0, 7, 2, 9],
 [array([ 72,  94, 125,  34], dtype=int64),
  array([ 72, 125, 108,  97], dtype=int64),
  array([111, 227, 185,  51], dtype=int64),
  array([ 72, 168, 125, 128], dtype=int64),
  array([115, 202, 145, 171], dtype=int64),
  array([128,  48, 185,  26], dtype=int64)],
 [5, 5, 1, 7, 0, 4]]

In [5]:
import numpy as np
df1=np.load('vastu_clean_data.pkl',allow_pickle=True)
df1[0]

[[1, 3, 0, 7, 2, 9, 13],
 [array([ 72,  94, 125,  34], dtype=int64),
  array([ 72, 125, 108,  97], dtype=int64),
  array([111, 227, 185,  51], dtype=int64),
  array([ 72, 168, 125, 128], dtype=int64),
  array([115, 202, 145, 171], dtype=int64),
  array([128,  48, 185,  26], dtype=int64),
  array([165, 217, 168, 202], dtype=int64)],
 [5, 5, 1, 7, 0, 4, 1],
 [7, 1, 6, 7, 2, 2, 7]]